### PR TITLE
♻️ Mint pages to community wallet

### PR DESCRIPTION
**Pull request by transmissions11**

### CODE REVIEW

**Comment by FrankieIsLost** [comment]
I don't think this works, there is no way to transfer pages minted to the GobblerReserve

**Comment by transmissions11** [comment]
wait wdym

**Comment by transmissions11** [comment]
@FrankieIsLost after further thought i realized there's no reason we should be sending pages to any reserve contract at all, extra overhead. introduced a new param for the community wallet, which in prod should just be a gnosis safe or something

**Comment by transmissions11** [comment]
@FrankieIsLost after further thought i realized there's no reason we should be sending pages to any reserve contract at all, extra overhead. introduced a new param for the community wallet, which in prod should just be a gnosis safe or something

**Comment by FrankieIsLost** [comment]
LGTM

**Pull request merged**
